# This continuous integration pipeline is triggered anytime a user pushes code to the repo.
# This pipeline builds the Wpf project, runs unit tests, then saves the MSIX build artifact.
name:  Windows CI

# Trigger on every master branch push and pull request
on:
  push:
    branches:
      - '*'
  pull_request:
    branches:
      - '*'

jobs:

  build:

    strategy:
      matrix:
        targetplatform: [x64]

    runs-on: windows-latest


    steps:
    - name: Checkout
      uses: actions/checkout@v2
      with:
        fetch-depth: 0 # avoid shallow clone so nbgv can do its work.


    - uses: actions/setup-python@v2
      with:
        python-version: '3.x'


    # Build the Windows Application Packaging project
    - name: Build a Windows App
      shell: cmd
      run: .\winbuild.bat


    # Upload the MSIX package: https://github.com/marketplace/actions/upload-artifact
    - name: Upload build artifacts
      uses: actions/upload-artifact@v1
      with:
        name: MSI Package
        path: dist
